import { useRouter } from 'next/router'
import Link from 'next/link'
import { ArrowLeft, ChevronRight, FileText, PackageCheck, Wrench } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import { getPartById, parts } from '@/data/parts'
import { SeoHead } from '@/components/seo/SeoHead'

const categoryNames: Record<string, string> = { engine: 'Engine', gearbox: 'Gearbox', axle: 'Axle', chassis: 'Chassis', 'cabin-body': 'Cabin & Body', other: 'Other' }

export default function PartDetailPage() {
  const router = useRouter()
  const { part } = router.query as { part: string }
  const partData = part ? getPartById(part) : undefined
  if (router.isFallback || !partData) return <div className="flex min-h-screen items-center justify-center bg-[var(--color-canvas)]"><div className="h-10 w-10 animate-spin rounded-full border-2 border-[var(--color-signal)] border-t-transparent" /></div>
  const path = `/parts/${part}`
  return <><SeoHead input={{ path, pageType: 'part', name: `${partData.name} ${partData.partNumber}`, description: partData.description, image: partData.image, breadcrumbs: [{ name: 'Home', path: '/' }, { name: 'Parts', path: '/parts' }, { name: partData.name, path }] }} /><Header /><main id="main" className="bg-[var(--color-panel)] pt-16 lg:pt-[72px]">
    <section className="border-b border-[var(--color-line)] bg-[var(--color-canvas)]"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex items-center gap-2 text-sm text-[var(--color-steel)]"><Link href="/" className="hover:text-[var(--color-signal-dark)]">Home</Link><ChevronRight className="h-4 w-4" /><Link href="/parts" className="hover:text-[var(--color-signal-dark)]">Parts</Link><ChevronRight className="h-4 w-4" /><span className="truncate">{partData.name}</span></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[minmax(0,1fr)_minmax(22rem,0.85fr)] lg:px-8 lg:py-14"><div className="flex min-h-[22rem] items-center justify-center rounded-2xl border border-[var(--color-line)] bg-[var(--color-canvas)] p-8"><img src={partData.image} alt={`${partData.name}, part number ${partData.partNumber}`} className="max-h-[28rem] max-w-full object-contain" /></div><div className="lg:sticky lg:top-24 lg:self-start"><p className="text-sm font-semibold uppercase tracking-[0.12em] text-[var(--color-signal-dark)]">{categoryNames[partData.category] || partData.category}</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.035em] text-[var(--color-ink)]">{partData.name}</h1><p className="mt-3 font-mono text-sm text-[var(--color-steel)]">Part number: {partData.partNumber}</p><p className="mt-6 leading-7 text-[var(--color-steel)]">{partData.description}</p><div className="mt-7 rounded-xl border border-[var(--color-line)] bg-[var(--color-canvas)] p-5"><div className="flex gap-3"><Wrench className="mt-0.5 h-5 w-5 shrink-0 text-[var(--color-signal-dark)]" /><div><h2 className="font-semibold text-[var(--color-ink)]">Compatibility confirmation</h2><p className="mt-1 text-sm leading-6 text-[var(--color-steel)]">Please provide the truck model or VIN for confirmation when compatibility is not stated in the catalogue.</p></div></div></div><Link href={`/contact?part=${encodeURIComponent(partData.id)}`} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-lg bg-[var(--color-signal)] px-5 text-sm font-semibold text-[var(--color-ink)] hover:bg-[var(--color-signal-dark)] hover:text-white">Request compatibility review <ChevronRight className="h-4 w-4" /></Link></div></section>
    <section className="border-y border-[var(--color-line)] bg-[var(--color-canvas)]"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[minmax(0,1fr)_20rem] lg:px-8"><div><h2 className="text-2xl font-bold tracking-[-0.025em] text-[var(--color-ink)]">Available specification data</h2><div className="mt-5 overflow-hidden rounded-xl border border-[var(--color-line)] bg-[var(--color-panel)]">{Object.entries(partData.specifications).map(([key, value]) => <div key={key} className="grid grid-cols-[minmax(9rem,0.7fr)_minmax(0,1.3fr)] gap-4 border-b border-[var(--color-line)] px-5 py-4 last:border-0"><span className="text-sm text-[var(--color-steel)]">{key}</span><span className="text-right text-sm font-semibold text-[var(--color-ink)]">{value}</span></div>)}</div></div><aside className="rounded-xl border border-[var(--color-line)] bg-[var(--color-panel)] p-5"><PackageCheck className="h-5 w-5 text-[var(--color-signal-dark)]" /><h2 className="mt-4 font-semibold text-[var(--color-ink)]">Before you enquire</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-[var(--color-steel)]"><li>Part number or product name</li><li>Truck model or VIN</li><li>Required quantity</li><li>Destination country or port</li></ul></aside></div></section>
    <section className="mx-auto flex max-w-7xl justify-between px-4 py-8 sm:px-6 lg:px-8"><Link href="/parts" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-[var(--color-signal-dark)] hover:text-[var(--color-ink)]"><ArrowLeft className="h-4 w-4" />Back to parts catalogue</Link><Link href="/contact" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-[var(--color-signal-dark)] hover:text-[var(--color-ink)]">Prepare an RFQ <FileText className="h-4 w-4" /></Link></section>
  </main><Footer /></>
}

export async function getStaticPaths() { return { paths: parts.map((part) => ({ params: { part: part.id } })), fallback: false } }
export async function getStaticProps() { return { props: {} } }
