import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';
import { ArrowRight, ChevronRight, Search } from 'lucide-react';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { SeoHead } from '@/components/seo/SeoHead';
import { parts, partCategories } from '@/data/parts';
import { filterParts } from '@/lib/procurement/filter-parts';

export default function PartsPage() {
  const router = useRouter();
  const [active, setActive] = useState('engine');
  const [query, setQuery] = useState('');
  useEffect(() => { const tab = router.query.tab; if (typeof tab === 'string' && partCategories.some((category) => category.id === tab)) setActive(tab); }, [router.query.tab]);
  const visible = filterParts(parts, { category: active, query });
  return <><SeoHead input={{ path: '/parts', pageType: 'website', name: 'Truck Parts Catalogue', description: 'Search available truck parts by part number, model and application, then submit your compatibility question.', image: '/images/parts/banner-parts.webp' }} /><Header />
    <main id="main" className="bg-[var(--color-panel)] pt-16 lg:pt-[72px]">
      <section className="relative isolate min-h-[300px] overflow-hidden bg-[var(--color-ink)] text-white"><img src="/images/parts/banner-parts.webp" alt="Truck parts catalogue" className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(16,35,39,.86),rgba(16,35,39,.25))]" /><div className="mx-auto flex min-h-[300px] max-w-7xl flex-col justify-end px-4 py-10 sm:px-6 lg:px-8"><div className="flex items-center gap-2 text-sm text-slate-100"><Link href="/">Home</Link><ChevronRight className="h-4 w-4" /><span>Parts</span></div><h1 className="mt-6 text-4xl font-extrabold">Truck Parts Catalogue</h1><p className="mt-3 max-w-2xl text-lg leading-7 text-slate-100">Search by part number, model or application, then confirm compatibility with your vehicle information.</p></div></section>
      <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-wrap gap-2">{partCategories.map((category) => <button key={category.id} onClick={() => setActive(category.id)} className={`min-h-11 border px-4 text-sm font-semibold ${active === category.id ? 'border-[var(--color-signal-dark)] bg-[var(--color-signal-dark)] text-white' : 'border-[var(--color-line)] text-[var(--color-ink)]'}`}>{category.name}</button>)}</div><label className="relative mt-6 block max-w-xl"><span className="sr-only">Search parts</span><Search className="absolute left-4 top-3.5 h-5 w-5 text-[var(--color-steel)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Part number, truck model or application" className="min-h-12 w-full border border-[var(--color-line)] bg-[var(--color-canvas)] py-3 pl-12 pr-4 text-sm" /></label><p className="mt-5 text-sm text-[var(--color-steel)]">{visible.length} parts match your current search.</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visible.map((part) => <Link key={part.id} href={`/parts/${part.id}`} className="group flex min-h-[18rem] flex-col border border-[var(--color-line)] bg-[var(--color-panel)] p-4 hover:border-[var(--color-signal)]"><div className="flex flex-1 items-center justify-center bg-[var(--color-canvas)]"><img src={part.image} alt={`${part.name}, part number ${part.partNumber}`} className="h-40 max-w-full object-contain" /></div><h2 className="mt-4 font-semibold text-[var(--color-ink)] group-hover:text-[var(--color-signal-dark)]">{part.name}</h2><p className="mt-1 font-mono text-xs text-[var(--color-steel)]">{part.partNumber}</p></Link>)}</div>{!visible.length && <div className="mt-5 border border-dashed border-[var(--color-line)] p-10 text-center text-[var(--color-steel)]">No matching parts. Try a different part number, model or category.</div>}</section>
      <section className="bg-[var(--color-ink)] py-12"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-5 px-4 sm:px-6 md:flex-row md:items-center lg:px-8"><div><h2 className="text-2xl font-bold text-[var(--color-panel)]">Need a compatibility review?</h2><p className="mt-2 text-[var(--color-canvas)]">Send the part number with your truck model or VIN through the RFQ form.</p></div><Link href="/contact" className="inline-flex min-h-11 items-center gap-2 bg-[var(--color-signal)] px-5 font-semibold text-[var(--color-ink)]">Prepare an RFQ <ArrowRight className="h-4 w-4" /></Link></div></section>
    </main><Footer /></>;
}
