import Link from 'next/link';
import { ChevronRight } from 'lucide-react';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import ProductCard from '@/components/product/ProductCard';
import { SeoHead } from '@/components/seo/SeoHead';
import { productCategories } from '@/data/siteConfig';
import { getProductsBySubcategory, type Product } from '@/data/products';

type Props = { category: { id: string; name: string; bannerImage: string }; subcategory: { id: string; name: string; image: string }; products: Product[] };

export default function ProductSubcategoryPage({ category, subcategory, products }: Props) {
  const path = `/products/${category.id}/${subcategory.id}`;
  return <div className="flex min-h-screen flex-col"><SeoHead input={{ path, pageType: 'website', name: `${subcategory.name} | ${category.name}`, description: `Browse ${subcategory.name} products in the ${category.name} range, including available images and technical parameters.`, image: subcategory.image || category.bannerImage, breadcrumbs: [{ name: 'Home', path: '/' }, { name: 'Products', path: '/products' }, { name: category.name, path: `/products/${category.id}` }, { name: subcategory.name, path }] }} /><Header /><main id="main" className="flex-grow bg-[var(--color-panel)] pt-16 lg:pt-[72px]"><section className="relative isolate min-h-[320px] overflow-hidden bg-[var(--color-ink)] text-white"><img src={subcategory.image || category.bannerImage} alt={`${subcategory.name} products`} className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(16,35,39,.86),rgba(16,35,39,.25))]" /><div className="mx-auto flex min-h-[320px] max-w-7xl flex-col justify-end px-4 py-10 sm:px-6 lg:px-8"><div className="flex items-center gap-2 text-sm text-slate-100"><Link href="/">Home</Link><ChevronRight className="h-4 w-4" /><Link href="/products">Products</Link><ChevronRight className="h-4 w-4" /><Link href={`/products/${category.id}`}>{category.name}</Link><ChevronRight className="h-4 w-4" /><span>{subcategory.name}</span></div><h1 className="mt-6 text-4xl font-extrabold sm:text-5xl">{subcategory.name}</h1><p className="mt-3 max-w-2xl text-lg leading-7 text-slate-100">Explore available {subcategory.name.toLowerCase()} models, imagery and published technical parameters.</p></div></section><section className="mx-auto max-w-7xl px-4 py-9 sm:px-6 lg:px-8"><div className="flex items-center justify-between border-b border-[var(--color-line)] pb-4"><p className="text-sm text-[var(--color-steel)]">{products.length} products in this category.</p><Link href={`/products/${category.id}`} className="text-sm font-semibold text-[var(--color-signal-dark)]">View all {category.name}</Link></div><div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{products.map((product) => <ProductCard key={product.id} product={product} />)}</div></section></main><Footer /></div>;
}

export async function getStaticPaths() { return { paths: productCategories.flatMap((category) => category.subcategories.map((subcategory) => ({ params: { category: category.id, subcategory: subcategory.id } }))), fallback: false }; }
export async function getStaticProps({ params }: { params: { category: string; subcategory: string } }) { const category = productCategories.find((item) => item.id === params.category); const subcategory = category?.subcategories.find((item) => item.id === params.subcategory); if (!category || !subcategory) return { notFound: true }; return { props: { category: { id: category.id, name: category.name, bannerImage: category.bannerImage }, subcategory, products: getProductsBySubcategory(category.id, subcategory.id) } }; }
