import { Plus, Sparkles, Trash2 } from 'lucide-react'
import type { ProductDetailContent } from '@/lib/product-detail/types'

type Props = {
  value?: ProductDetailContent
  onChange: (value: ProductDetailContent) => void
  onGenerate: () => void
}

const inputClass = 'w-full rounded-lg border px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-[#26807d]'

export function ProductDetailContentEditor({ value, onChange, onGenerate }: Props) {
  const update = <K extends keyof ProductDetailContent>(key: K, next: ProductDetailContent[K]) => value && onChange({ ...value, [key]: next })

  return <div className="space-y-6 rounded-xl bg-white p-6 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">产品详情与 SEO 内容</h2><p className="mt-1 text-sm text-gray-500">根据当前产品事实生成草稿，保存前可以逐项修改；不会调用外部 AI。</p></div><button type="button" onClick={onGenerate} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#26807d] px-4 text-sm font-semibold text-white"><Sparkles size={16} />自动补全详情 SEO 内容</button></div>

    {!value ? <p className="rounded-lg border border-dashed p-5 text-sm text-gray-500">点击自动补全后开始编辑。现有产品加载时会自动显示已保存或已生成的内容。</p> : <>
      <section><label className="mb-2 block text-sm font-semibold">Performance 总述</label><textarea className={inputClass} rows={4} value={value.performanceSummary} onChange={(event) => update('performanceSummary', event.target.value)} /></section>

      <section><h3 className="text-sm font-semibold">Performance 图文项</h3><div className="mt-3 grid gap-3 lg:grid-cols-3">{value.performanceItems.map((item, index) => <div key={index} className="space-y-2 rounded-lg border p-3"><input aria-label={`Performance ${index + 1} 标题`} className={inputClass} value={item.title} onChange={(event) => { const next = [...value.performanceItems]; next[index] = { ...item, title: event.target.value }; update('performanceItems', next) }} /><input aria-label={`Performance ${index + 1} 图片`} className={inputClass} value={item.image} onChange={(event) => { const next = [...value.performanceItems]; next[index] = { ...item, image: event.target.value }; update('performanceItems', next) }} /><textarea aria-label={`Performance ${index + 1} 描述`} className={inputClass} rows={4} value={item.description} onChange={(event) => { const next = [...value.performanceItems]; next[index] = { ...item, description: event.target.value }; update('performanceItems', next) }} /></div>)}</div></section>

      <section><h3 className="text-sm font-semibold">画廊 SEO 描述</h3><div className="mt-3 grid gap-3 lg:grid-cols-2">{value.gallery.map((item, index) => <div key={`${item.image}-${index}`} className="space-y-2 rounded-lg border p-3"><input aria-label={`画廊 ${index + 1} 图片`} className={inputClass} value={item.image} onChange={(event) => { const next = [...value.gallery]; next[index] = { ...item, image: event.target.value }; update('gallery', next) }} /><input aria-label={`画廊 ${index + 1} 标题`} className={inputClass} value={item.title} onChange={(event) => { const next = [...value.gallery]; next[index] = { ...item, title: event.target.value }; update('gallery', next) }} /><input aria-label={`画廊 ${index + 1} alt`} className={inputClass} value={item.alt} onChange={(event) => { const next = [...value.gallery]; next[index] = { ...item, alt: event.target.value }; update('gallery', next) }} /><textarea aria-label={`画廊 ${index + 1} 描述`} className={inputClass} rows={3} value={item.description} onChange={(event) => { const next = [...value.gallery]; next[index] = { ...item, description: event.target.value }; update('gallery', next) }} /></div>)}</div></section>

      <section><h3 className="text-sm font-semibold">应用场景</h3><div className="mt-3 grid gap-3 lg:grid-cols-2">{value.applicationAreas.map((item, index) => <div key={index} className="space-y-2 rounded-lg border p-3"><input aria-label={`应用场景 ${index + 1} 标题`} className={inputClass} value={item.title} onChange={(event) => { const next = [...value.applicationAreas]; next[index] = { ...item, title: event.target.value }; update('applicationAreas', next) }} /><input aria-label={`应用场景 ${index + 1} 图片`} className={inputClass} value={item.image} onChange={(event) => { const next = [...value.applicationAreas]; next[index] = { ...item, image: event.target.value }; update('applicationAreas', next) }} /><textarea aria-label={`应用场景 ${index + 1} 描述`} className={inputClass} rows={3} value={item.description} onChange={(event) => { const next = [...value.applicationAreas]; next[index] = { ...item, description: event.target.value }; update('applicationAreas', next) }} /><textarea aria-label={`应用场景 ${index + 1} 要点`} className={inputClass} rows={3} value={item.bullets.join('\n')} onChange={(event) => { const next = [...value.applicationAreas]; next[index] = { ...item, bullets: event.target.value.split('\n').filter(Boolean) }; update('applicationAreas', next) }} /></div>)}</div></section>

      <section><h3 className="text-sm font-semibold">解决方案</h3><div className="mt-3 grid gap-3 lg:grid-cols-2">{value.solutions.map((item, index) => <div key={index} className="space-y-2 rounded-lg border p-3"><input aria-label={`解决方案 ${index + 1} 标题`} className={inputClass} value={item.title} onChange={(event) => { const next = [...value.solutions]; next[index] = { ...item, title: event.target.value }; update('solutions', next) }} /><input aria-label={`解决方案 ${index + 1} 图片`} className={inputClass} value={item.image} onChange={(event) => { const next = [...value.solutions]; next[index] = { ...item, image: event.target.value }; update('solutions', next) }} /><textarea aria-label={`解决方案 ${index + 1} 描述`} className={inputClass} rows={3} value={item.description} onChange={(event) => { const next = [...value.solutions]; next[index] = { ...item, description: event.target.value }; update('solutions', next) }} /><textarea aria-label={`解决方案 ${index + 1} 要点`} className={inputClass} rows={3} value={item.bullets.join('\n')} onChange={(event) => { const next = [...value.solutions]; next[index] = { ...item, bullets: event.target.value.split('\n').filter(Boolean) }; update('solutions', next) }} /></div>)}</div></section>

      <section><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-semibold">独立 FAQ</h3><p className="mt-1 text-xs text-gray-500">每款产品保留 4–6 个问答。</p></div><button type="button" disabled={value.faqs.length >= 6} onClick={() => update('faqs', [...value.faqs, { question: '', answer: '' }])} className="inline-flex min-h-11 items-center gap-1 text-sm text-[#26807d] disabled:opacity-40"><Plus size={16} />添加 FAQ</button></div><div className="mt-3 space-y-3">{value.faqs.map((item, index) => <div key={index} data-faq-item={index} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[1fr_auto]"><div className="space-y-2"><input aria-label={`FAQ ${index + 1} 问题`} className={inputClass} value={item.question} onChange={(event) => { const next = [...value.faqs]; next[index] = { ...item, question: event.target.value }; update('faqs', next) }} /><textarea aria-label={`FAQ ${index + 1} 答案`} className={inputClass} rows={3} value={item.answer} onChange={(event) => { const next = [...value.faqs]; next[index] = { ...item, answer: event.target.value }; update('faqs', next) }} /></div><button type="button" aria-label={`删除 FAQ ${index + 1}`} disabled={value.faqs.length <= 4} onClick={() => update('faqs', value.faqs.filter((_, itemIndex) => itemIndex !== index))} className="min-h-11 p-2 text-red-500 disabled:opacity-30"><Trash2 size={16} /></button></div>)}</div></section>
    </>}
  </div>
}
