import type { ChangeEvent } from 'react';
import type { ProductFilterState } from '@/lib/procurement/types';

interface ProductFiltersProps { drives: string[]; applications: string[]; value: ProductFilterState; onChange: (value: ProductFilterState) => void; }
const toggle = (values: string[], value: string) => values.includes(value) ? values.filter((item) => item !== value) : [...values, value];

export default function ProductFilters({ drives, applications, value, onChange }: ProductFiltersProps) {
  const checkbox = (key: 'drive' | 'applications', item: string) => ({ checked: value[key].includes(item), onChange: () => onChange({ ...value, [key]: toggle(value[key], item) }) });
  const number = (key: 'powerMin' | 'powerMax') => (event: ChangeEvent<HTMLInputElement>) => onChange({ ...value, [key]: event.target.value ? Number(event.target.value) : undefined });
  return <aside className="border border-[var(--color-line)] bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold text-[var(--color-ink)]">Filter vehicles</h2><button type="button" className="text-xs font-bold text-[var(--color-signal)]" onClick={() => onChange({ drive: [], applications: [] })}>Reset</button></div><fieldset className="mt-5"><legend className="text-xs font-bold uppercase tracking-[.1em] text-[var(--color-steel)]">Drive form</legend><div className="mt-3 space-y-2">{drives.map((drive) => <label key={drive} className="flex items-center gap-2 text-sm text-[var(--color-steel)]"><input type="checkbox" {...checkbox('drive', drive)} />{drive}</label>)}</div></fieldset><fieldset className="mt-6"><legend className="text-xs font-bold uppercase tracking-[.1em] text-[var(--color-steel)]">Application</legend><div className="mt-3 space-y-2">{applications.map((application) => <label key={application} className="flex items-center gap-2 text-sm capitalize text-[var(--color-steel)]"><input type="checkbox" {...checkbox('applications', application)} />{application}</label>)}</div></fieldset><div className="mt-6"><p className="text-xs font-bold uppercase tracking-[.1em] text-[var(--color-steel)]">Power (hp)</p><div className="mt-3 grid grid-cols-2 gap-2"><input aria-label="Minimum power" type="number" placeholder="Min" value={value.powerMin ?? ''} onChange={number('powerMin')} className="w-full border border-[var(--color-line)] px-2 py-2 text-sm" /><input aria-label="Maximum power" type="number" placeholder="Max" value={value.powerMax ?? ''} onChange={number('powerMax')} className="w-full border border-[var(--color-line)] px-2 py-2 text-sm" /></div></div></aside>;
}
