import type { ChangeEvent } from 'react';
import type { ProductFilterState } from '@/lib/procurement/types';

interface ProductFiltersProps { className?: string; drives: string[]; applications: string[]; value: ProductFilterState; onChange: (value: ProductFilterState) => void; }
const toggle = (values: string[], value: string) => values.includes(value) ? values.filter((item) => item !== value) : [...values, value];

export default function ProductFilters({ className = '', drives, applications, value, onChange }: ProductFiltersProps) {
  const checkbox = (key: 'drive' | 'applications', item: string) => ({ checked: value[key].includes(item), onChange: () => onChange({ ...value, [key]: toggle(value[key], item) }) });
  const number = (key: 'powerMin' | 'powerMax') => (event: ChangeEvent<HTMLInputElement>) => onChange({ ...value, [key]: event.target.value ? Number(event.target.value) : undefined });
  return <aside className={`border border-[var(--industrial-line)] bg-[var(--industrial-panel)] p-5 ${className}`}><div className="flex items-center justify-between gap-3"><h2 className="font-bold uppercase text-[var(--industrial-text)]">Filter vehicles</h2><button type="button" className="min-h-11 text-xs font-bold uppercase tracking-[0.08em] text-[var(--industrial-accent)]" onClick={() => onChange({ drive: [], applications: [] })}>Clear all</button></div><fieldset className="mt-5"><legend className="text-xs font-bold uppercase tracking-[.1em] text-[var(--industrial-muted)]">Drive form</legend><div className="mt-3 space-y-2">{drives.map((drive) => <label key={drive} className="flex min-h-8 items-center gap-3 text-sm text-[var(--industrial-muted)]"><input type="checkbox" {...checkbox('drive', drive)} className="h-4 w-4 accent-[var(--industrial-accent)]" />{drive}</label>)}</div></fieldset><fieldset className="mt-6"><legend className="text-xs font-bold uppercase tracking-[.1em] text-[var(--industrial-muted)]">Application</legend><div className="mt-3 space-y-2">{applications.map((application) => <label key={application} className="flex min-h-8 items-center gap-3 text-sm capitalize text-[var(--industrial-muted)]"><input type="checkbox" {...checkbox('applications', application)} className="h-4 w-4 accent-[var(--industrial-accent)]" />{application}</label>)}</div></fieldset><div className="mt-6"><p className="text-xs font-bold uppercase tracking-[.1em] text-[var(--industrial-muted)]">Power (hp)</p><div className="mt-3 grid grid-cols-2 gap-2"><input aria-label="Minimum power" type="number" placeholder="Min" value={value.powerMin ?? ''} onChange={number('powerMin')} className="min-h-11 w-full border border-[var(--industrial-line)] bg-[#081113] px-2 py-2 text-sm text-[var(--industrial-text)]" /><input aria-label="Maximum power" type="number" placeholder="Max" value={value.powerMax ?? ''} onChange={number('powerMax')} className="min-h-11 w-full border border-[var(--industrial-line)] bg-[#081113] px-2 py-2 text-sm text-[var(--industrial-text)]" /></div></div></aside>;
}
