import Head from 'next/head';
import Link from 'next/link';
import { SiteImage } from '@/components/SiteImage';
import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';

type ImageItem = { src: string; alt: string; label?: string };

export default function AboutPageLayout({ title, description, children, gallery = [] }: { title: string; description: string; children: React.ReactNode; gallery?: ImageItem[] }) {
  return <div className="flex min-h-screen flex-col"><Head><title>{title} | SINOTRUK TEAM</title><meta name="description" content={description} /></Head><Header /><main className="flex-grow bg-[var(--color-canvas)] pt-16 lg:pt-[72px]"><section className="relative isolate overflow-hidden bg-[var(--color-ink)]"><SiteImage src="/images/reference/banner-about-1.webp" alt="Commercial truck manufacturing" fill priority sizes="100vw" className="-z-20 object-cover opacity-40" /><div className="absolute inset-0 -z-10 bg-[var(--color-ink)]/65" /><div className="mx-auto max-w-6xl px-4 py-20 text-white sm:px-6 lg:px-8"><p className="text-sm font-semibold tracking-[0.12em] text-teal-100">ABOUT US</p><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">{title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-100">{description}</p></div></section><div className="mx-auto max-w-6xl px-4 py-14 sm:px-6 lg:px-8">{children}{gallery.length > 0 && <section className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{gallery.map((image) => <figure key={image.src} className="overflow-hidden bg-white shadow-sm"><div className="relative aspect-[4/3]"><SiteImage src={image.src} alt={image.alt} fill sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" className="object-cover" /></div>{image.label && <figcaption className="p-4 text-sm font-semibold text-[var(--color-ink)]">{image.label}</figcaption>}</figure>)}</section>}<section className="mt-14 bg-[var(--color-ink)] px-6 py-10 text-white sm:px-10"><h2 className="text-2xl font-extrabold">Explore the product range</h2><p className="mt-3 max-w-2xl leading-7 text-slate-200">Browse commercial vehicles, parts and service information, or send an enquiry with your operating requirements.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/products" className="bg-[var(--color-signal)] px-5 py-3 text-sm font-bold hover:bg-[var(--color-signal-dark)]">Browse Products</Link><Link href="/contact" className="border border-white/50 px-5 py-3 text-sm font-bold hover:bg-white/10">Contact Us</Link></div></section></div></main><Footer /></div>;
}
